//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rakuten.IO.Delimited {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rakuten.IO.Delimited.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the processing of a CSV file..
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to map value &apos;{0}&apos; to type &apos;{1}&apos;. (Field=&apos;{2}&apos;, Index=&apos;{3}&apos;, Property=&apos;{4}&apos;)..
        /// </summary>
        internal static string FieldFormatExceptionMessage {
            get {
                return ResourceManager.GetString("FieldFormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required header &apos;{0}&apos; is not present in the file..
        /// </summary>
        internal static string HeaderMissingExceptionMessage {
            get {
                return ResourceManager.GetString("HeaderMissingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field index was missing for property &apos;{0}&apos;.
        /// </summary>
        internal static string IndexMissingExceptionMessage {
            get {
                return ResourceManager.GetString("IndexMissingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified default value &apos;{0}&apos; is not valid for the property &apos;{1}&apos; of type &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidDefaultExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidDefaultExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to map string value &apos;{0}&apos; to Enum of type &apos;{1}&apos;. Ensure that an appropriate Enum value exists. If Enum Descriptions are being used, ensure that &apos;useDescriptions&apos; is set to true on the FieldEnumConverter..
        /// </summary>
        internal static string InvalidEnumValueExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidEnumValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to read the CSV file at line {0}..
        /// </summary>
        internal static string ReadLineExceptionMessage {
            get {
                return ResourceManager.GetString("ReadLineExceptionMessage", resourceCulture);
            }
        }
    }
}
