//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rakuten.Rmsg.ProductQuery.Web.Http.Tests.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.product1 = new HashSet<product>();
        }
    
        public string GRAN { get; set; }
        public string improvedGRAN { get; set; }
        public System.Guid manufacturerID { get; set; }
        public string manufacturerPartNumber { get; set; }
        public System.Guid productCategoryID { get; set; }
        public byte[] GTINhash { get; set; }
        public System.DateTime createTime { get; set; }
        public System.DateTime updateTime { get; set; }
    
        public virtual ICollection<product> product1 { get; set; }
        public virtual product product2 { get; set; }
    }
}
