//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rakuten.Rmsg.ProductQuery.Web.Http.Tests.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class rmsgProductQuery
    {
        public rmsgProductQuery()
        {
            this.rmsgProductQueryItems = new HashSet<rmsgProductQueryItem>();
        }
    
        public System.Guid rmsgProductQueryID { get; set; }
        public System.Guid rmsgProductQueryGroupID { get; set; }
        public short index { get; set; }
        public System.DateTime dateCreated { get; set; }
        public byte rmsgProductQueryStatusID { get; set; }
        public string uri { get; set; }
        public string culture { get; set; }
    
        public virtual rmsgProductQueryGroup rmsgProductQueryGroup { get; set; }
        public virtual rmsgProductQueryStatu rmsgProductQueryStatu { get; set; }
        public virtual ICollection<rmsgProductQueryItem> rmsgProductQueryItems { get; set; }
    }
}
