//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rakuten.Rmsg.ProductQuery.Web.Http.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductQueryDbContext : DbContext
    {
        public ProductQueryDbContext()
            : base("name=ProductQueryDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rmsgProductQuery> rmsgProductQueries { get; set; }
        public virtual DbSet<rmsgProductQueryGroup> rmsgProductQueryGroups { get; set; }
        public virtual DbSet<rmsgProductQueryItem> rmsgProductQueryItems { get; set; }
        public virtual DbSet<rmsgProductQueryStatu> rmsgProductQueryStatus { get; set; }
    }
}
