//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rakuten.Rmsg.ProductQuery.Web.Http.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class rmsgProductQueryItem
    {
        public System.Guid rmsgProductQueryID { get; set; }
        public string gtin { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
    
        public virtual rmsgProductQuery rmsgProductQuery { get; set; }
    }
}
